### ISSUE TITLE
Spell checker / auto correct not working

### ISSUE THREAD

**Issue by jmartinesp** [matrix-org/matrix-rich-text-editor#277]
Some users have mentioned that the automatic spell checking is not working.

- https://github.com/vector-im/element-android/issues/7463

**Comment by jonnyandrew** [comment]
## Fndings (Android)

The spell check is running inside the editor but sometimes the spell check errors disappear and reappear.

## Problem
This seems to be related to how the rich text editor works internally, replacing the entire contents of the `EditText` on every key press and clearing the `Span`s applied by the spell checker.

## Solution
One solution could be to return incremental updates from the Rust model so that the app needs only to replace changed text and can thus preserve spell check suggestions. 

Related to-do:
https://github.com/matrix-org/matrix-rich-text-editor/blob/70a0e5074f106604e7eafc8e78df7e18527116de/crates/wysiwyg/src/composer_model/replace_text.rs#L183-L185

**Comment by langleyd** [comment]
Markup and correction for autocorrection now works well on the latest.
